export default {
  "00": {
    divisionStep: 21,
    cellDivide: 0.9,
    cellFill: 0.9,
    cellTwoDivisions: 0.9,
    showPartial: false,
  },
  "01": {
    divisionStep: 21,
    cellDivide: 0.85,
    cellFill: 1,
    cellTwoDivisions: 1,
    showPartial: false,
  },
  "02": {
    divisionStep: 15,
    cellDivide: 1,
    cellFill: 1,
    cellTwoDivisions: 1,
    showPartial: false,
  },
  "03": {
    divisionStep: 12,
    cellDivide: 1,
    cellFill: 0.9,
    cellTwoDivisions: 1,
    showPartial: false,
  },
  "04": {
    divisionStep: 15,
    cellDivide: 0.8,
    cellFill: 1,
    cellTwoDivisions: 0.02,
    showPartial: false,
  },
  "05": {
    divisionStep: 19,
    cellDivide: 0.6,
    cellFill: 1,
    cellTwoDivisions: 1,
    showPartial: false,
  },
  "06": {
    divisionStep: 19,
    cellDivide: 0.6,
    cellFill: 0.7,
    cellTwoDivisions: 1,
    showPartial: false,
  },
  "07": {
    divisionStep: 6,
    cellDivide: 0.1,
    cellFill: 0.2,
    cellTwoDivisions: 0.1,
    showPartial: false,
  },
  "08": {
    divisionStep: 26,
    cellDivide: 0.1,
    cellFill: 0.2,
    cellTwoDivisions: 0.1,
    showPartial: false,
  },
  "09": {
    divisionStep: 26,
    cellDivide: 0.1,
    cellFill: 0.2,
    cellTwoDivisions: 0,
    showPartial: false,
  },
  "10": {
    divisionStep: 23,
    cellDivide: 1,
    cellFill: 0.1,
    cellTwoDivisions: 0,
    showPartial: false,
  },
  "11": {
    divisionStep: 15,
    cellDivide: 1,
    cellFill: 0.1,
    cellTwoDivisions: 0.5,
    showPartial: false,
  },
  "13": {
    divisionStep: 6,
    cellDivide: 0.4,
    cellFill: 0.7,
    cellTwoDivisions: 0.5,
    showPartial: false,
  }
}
